---
- name: Install Nginx config
  gather_facts: True
  hosts: all
  vars:
    domain_name: 'pentest.rohitsalecha.com'
  tasks:
    - name: Write nginx conf file
      template:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: a+rx
      become: yes

    - name: Write nginx default conf file
      template:
        src: default.conf.j2
        dest: /etc/nginx/conf.d/default.conf
        owner: root
        group: root
        mode: a+rx
      become: yes

    - name: restart nginx
      service: name=nginx state=restarted enabled=yes
      become: yes